module.exports = {
  docs: [
    {
      type: "category",
      label: "Docs",
      items: ["index", "install", "usage", "example", "cheatsheet"],
    },
  ],
  api: {
    APIs: [
      "apis",
      "accessibilityinfo",
      "actionsheetios",
      "alert",
      "animated",
      "animationframe",
      "appregistry",
      "appstate",
      "backhandler",
      "dimensions",
      "easing",
      "event",
      "global",
      "interactionmanager",
      "keyboard",
      "layoutanimation",
      "linking",
      "packager",
      "panresponder",
      "permissionsandroid",
      "pixelratio",
      "platform",
      "platformcolor",
      "settings",
      "share",
      "style",
      "stylesheet",
      "toastandroid",
      "vibration",
      // "accessibilityinfo",
      // "alert",
      // "animated",
      // "animatedvalue",
      // "animatedvaluexy",
      // "appearance",
      // "appregistry",
      // "appstate",
      // "devsettings",
      // "dimensions",
      // "easing",
      // "interactionmanager",
      // "keyboard",
      // "layoutanimation",
      // "linking",
      // "panresponder",
      // "pixelratio",
      // "platform",
      // "platformcolor",
      // "share",
      // "stylesheet",
      // "systrace",
      // "transforms",
      // "vibration",
      // {
      //   type: "category",
      //   label: "Hooks",
      //   collapsed: false,
      //   items: ["usecolorscheme", "usewindowdimensions"],
      // },
      // {
      //   type: "category",
      //   label: "Android APIs",
      //   collapsed: false,
      //   items: ["backhandler", "permissionsandroid", "toastandroid"],
      // },
      // {
      //   type: "category",
      //   label: "iOS APIs",
      //   collapsed: false,
      //   items: ["actionsheetios", "dynamiccolorios", "settings"],
      // },
    ],
  },
  components: {
    Components: [
      "components",
      "activityindicator",
      "button",
      "drawerlayoutandroid",
      "flatlist",
      "image",
      "imagebackground",
      "inputaccessoryview",
      "keyboardavoidingview",
      "maskedviewios",
      "modal",
      "pressable",
      "refreshcontrol",
      "safeareaview",
      "scrollview",
      "sectionlist",
      "statusbar",
      "switch",
      "text",
      "textinput",
      "touchablehighlight",
      "touchablenativefeedback",
      "touchableopacity",
      "touchablewithoutfeedback",
      "view",
      "virtualizedlist",
      // "components-and-apis",
      // "activityindicator",
      // "button",
      // "flatlist",
      // "image",
      // "imagebackground",
      // "keyboardavoidingview",
      // "modal",
      // "pressable",
      // "refreshcontrol",
      // "scrollview",
      // "sectionlist",
      // "statusbar",
      // "switch",
      // "text",
      // "textinput",
      // "touchablehighlight",
      // "touchableopacity",
      // "touchablewithoutfeedback",
      // "view",
      // "virtualizedlist",
      // {
      //   type: "category",
      //   label: "Android Components",
      //   collapsed: false,
      //   items: ["drawerlayoutandroid", "touchablenativefeedback"],
      // },
      // {
      //   type: "category",
      //   label: "iOS Components",
      //   collapsed: false,
      //   items: ["inputaccessoryview", "safeareaview"],
      // },
    ],
    // Props: [
    //   "image-style-props",
    //   "layout-props",
    //   "shadow-props",
    //   "text-style-props",
    //   "view-style-props",
    // ],
    // "Object Types": [
    //   "layoutevent",
    //   "pressevent",
    //   "react-node",
    //   "rect",
    //   "viewtoken",
    // ],
  },
};
